SELECT
    BBS.AUTHOR_ID,
    A.AUTHOR_NAME,
    BBS.CATEGORY,
    SUM(BOOK_TOTAL_PRICE) AS TOTAL_PRICE
FROM
    (SELECT
        B.AUTHOR_ID,
        B.CATEGORY,
        (BS.SALE_COUNT * B.PRICE) AS BOOK_TOTAL_PRICE
    FROM
        (SELECT
            BOOK_ID,
            SUM(SALES) AS SALE_COUNT
        FROM
            BOOK_SALES
        WHERE
            DATE_FORMAT(SALES_DATE, '%y-%m') = '22-01'
        GROUP BY
            BOOK_ID) AS BS INNER JOIN BOOK AS B ON BS.BOOK_ID = B.BOOK_ID) AS BBS
            INNER JOIN AUTHOR AS A ON BBS.AUTHOR_ID = A.AUTHOR_ID
GROUP BY
    BBS.AUTHOR_ID, BBS.CATEGORY
ORDER BY
    BBS.AUTHOR_ID, BBS.CATEGORY DESC