SELECT P.PRODUCT_CODE, (SUM(SALES_AMOUNT) * P.PRICE) AS SALES
FROM PRODUCT AS P LEFT JOIN OFFLINE_SALE AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCT_ID IS NOT NULL
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC;