SELECT
    T.ANIMAL_ID, T.NAME
FROM
    (SELECT F.ANIMAL_ID, F.NAME, DATEDIFF(S.DATETIME, F.DATETIME) AS PERIOD
    FROM
        ANIMAL_INS AS F INNER JOIN ANIMAL_OUTS AS S
        ON F.ANIMAL_ID = S.ANIMAL_ID
    ORDER BY
        PERIOD DESC) AS T
LIMIT
    2;