WITH USER_NUM AS(
    SELECT COUNT(*) AS JOINED_USER
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USER,
    ROUND(COUNT(DISTINCT USER_ID)/JOINED_USER, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE, USER_NUM
WHERE
    USER_ID IN (SELECT DISTINCT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)