WITH RECURSIVE ANC AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION
    SELECT E.ID, E.PARENT_ID, GENERATION + 1
    FROM ECOLI_DATA AS E, ANC AS A
    WHERE E.PARENT_ID = A.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM ANC
WHERE ID NOT IN (SELECT PARENT_ID
                 FROM ANC
                 WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION