WITH FRONT_SKILL AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS, FRONT_SKILL
WHERE SKILL_CODE & CODE != 0
ORDER BY ID