SELECT
    EMP_NO,
    EMP_NAME,
    CASE 
        WHEN AVG_SCORE >= 96 THEN 'S'
        WHEN AVG_SCORE >= 90 THEN 'A'
        WHEN AVG_SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE 
        WHEN AVG_SCORE >= 96 THEN (SAL*0.2)
        WHEN AVG_SCORE >= 90 THEN (SAL*0.15)
        WHEN AVG_SCORE >= 80 THEN (SAL*0.1)
        ELSE 0
    END AS BONUS
FROM
    (SELECT
        HE.EMP_NO,
        HE.EMP_NAME,
        HE.SAL,
        AVG(HG.SCORE) AS AVG_SCORE
    FROM
        HR_EMPLOYEES AS HE INNER JOIN HR_GRADE AS HG
        ON HE.EMP_NO = HG.EMP_NO
    GROUP BY
        HE.EMP_NO) AS TT
ORDER BY
    EMP_NO