SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS P LEFT JOIN REST_REVIEW AS R
ON P.MEMBER_ID = R.MEMBER_ID
WHERE P.MEMBER_ID = (SELECT MEMBER_ID
                     FROM (SELECT MEMBER_ID, COUNT(MEMBER_ID) AS COUNT
                           FROM REST_REVIEW
                           GROUP BY MEMBER_ID
                           ORDER BY COUNT DESC
                           LIMIT 1) AS T)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;
                           