SELECT
    ID,
    FISH_NAME,
    LENGTH
FROM
    (SELECT
        ID,
        FISH_NAME,
        LENGTH,
        MAX(LENGTH) OVER(PARTITION BY FISH_NAME) AS MAX_LENGTH
    FROM
        FISH_INFO AS F LEFT JOIN FISH_NAME_INFO AS S
        ON F.FISH_TYPE = S.FISH_TYPE) AS F
WHERE
    MAX_LENGTH = LENGTH
ORDER BY ID;