SELECT
    S.INGREDIENT_TYPE,
    SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM
    FIRST_HALF AS F LEFT JOIN ICECREAM_INFO AS S
    ON F.FLAVOR = S.FLAVOR
GROUP BY S.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER
    