SELECT 
    F.CATEGORY,
    SUM(S.SALES) AS TOTAL_SALES
FROM 
    BOOK AS F LEFT JOIN BOOK_SALES AS S 
    ON F.BOOK_ID = S.BOOK_ID
WHERE 
    DATE_FORMAT(S.SALES_DATE, "%Y-%m") = '2022-01'
GROUP BY F.CATEGORY
ORDER BY F.CATEGORY;