WITH SKILL AS (
    SELECT 'Front End' AS COMPETENCY, SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
    UNION ALL
    SELECT 'Python' AS COMPETENCY, CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
    UNION ALL
    SELECT 'C#' AS COMPETENCY, CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
)

SELECT *
FROM (SELECT 
        CASE 
            WHEN (SKILL_CODE & (SELECT CODE FROM SKILL WHERE COMPETENCY = 'Front End')) != 0 
             AND (SKILL_CODE & (SELECT CODE FROM SKILL WHERE COMPETENCY = 'Python')) != 0 THEN 'A'
            WHEN (SKILL_CODE & (SELECT CODE FROM SKILL WHERE COMPETENCY = 'C#')) != 0 THEN 'B'
            WHEN (SKILL_CODE & (SELECT CODE FROM SKILL WHERE COMPETENCY = 'Front End')) != 0 THEN 'C'
            ELSE NULL
        END AS GRADE,
      ID,EMAIL
      FROM DEVELOPERS) AS F
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID
